### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by ivop**

### CODE REVIEW

**Comment by ivop** [comment]
Sorry, I meant to merge a branch in my fork :(

**Comment by ClassicOldSong** [comment]
Hi, it's interesting to see this fork, will you contribute it to the main repo in the future?

**Comment by ivop** [comment]
Hi, yes, that's the plan. I'm not finished yet, but most of the loaders are included now and synced with adplug upstream. I still want to add a probe mode and refactor the vgm writer. I'll let you know when I'm done. Would you mind if I converted main and VgmOpl from tabs to spaces? I'll leave the Formats alone as that simplifies keeping track of upstream changes.

**Comment by ClassicOldSong** [comment]
Actually we would like keep using tabs. For the adplug part it doesn't really matter. Anyway thanks for the upgrade!

**Comment by ivop** [comment]
I have kept the tabs in place and fixed some of the stray spaces I accidentally introduced. I'll send a pull request when I'm finished with it.

**Pull request closed without merging**
